# site name
prefixName: 太阳
siteName: 鸽鸽棒
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: taiyanggegebang.github.io
description: 让我们简单处理一下，嗯，效果很不错。
cdn: https://cdn.jsdelivr.net/gh/taiyanggegebang/cdn@main/
pjax: 1
# 1开启
mathjax: 0

notice: Motion Design 系统教学
lazyloadImg: https://cdn.jsdelivr.net/gh/taiyanggegebang/cdn/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
  } }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
  } }
  小黑屋: {path: /, fa: fa-times , submenus: {
    群(1): {path: /xiaoheiwu/01/, fa: fa-id-badge},
    群(2): {path: /xiaoheiwu/02/, fa: fa-id-badge},
    群(3): {path: /xiaoheiwu/03/, fa: fa-id-badge},
    群(4): {path: /xiaoheiwu/04/, fa: fa-id-badge},
    群(5): {path: /xiaoheiwu/05/, fa: fa-id-badge},
  } }

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/taiyanggegebang/cdn/img/cover/2021-08-07.webp
  - https://cdn.jsdelivr.net/gh/taiyanggegebang/cdn/img/cover/2021-08-21.webp
  - https://cdn.jsdelivr.net/gh/taiyanggegebang/cdn/img/cover/2021-09-04.webp
  - https://cdn.jsdelivr.net/gh/taiyanggegebang/cdn/img/cover/2021-09-18.webp
  - https://cdn.jsdelivr.net/gh/taiyanggegebang/cdn/img/cover/2021-10-02.webp
  - https://cdn.jsdelivr.net/gh/taiyanggegebang/cdn/img/cover/2021-10-16.webp
  - https://cdn.jsdelivr.net/gh/taiyanggegebang/cdn/img/cover/2021-10-30.webp
  - https://cdn.jsdelivr.net/gh/taiyanggegebang/cdn/img/cover/2021-11-13.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dim

# startdash url, title, desc img
startdash: 
  - {url: https://www.bilibili.com/video/BV1TL4y1q7Ef, title: AE教程, desc: 苹果十月发布会预告效果制作, img: /img/cover/2021-10-30.webp}
  - {url: https://www.bilibili.com/video/BV1Mh411s7hP, title: AE教程, desc: 微软全新3D表情包MG动画制作, img: /img/cover/2021-09-04.webp}
  - {url: https://www.bilibili.com/video/BV1xq4y1Q7pH, title: AE教程, desc: 东京奥运会动态图标效果制作, img: /img/cover/2021-08-07.webp}



# your site build time or founded date
siteBuildingTime: 11/17/2021

#social  url, img PC端配置
social:
  github: {url: http://github.com/Dongyifengs, img: /img/social/github.png}
  github2: {url: http://github.com/taiyanggegebang, img: /img/social/github.png} 
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  wechat2: {url: /#, qrcode: /img/custom/wechat2.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/Dongyifengs, img: /img/social/github.png}
  github2: {url: http://github.com/taiyanggegebang, img: /img/social/github.png} 
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  wechat2: {url: /#, qrcode: /img/custom/wechat2.jpg, img: /img/social/wechat.png}

donate:
  paypal: 
  alipay: img/custom/wechat2.jpg
  wechat: img/custom/wechat.jpg
  wechatSQ: 

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/taiyanggegebang/cdn@main/
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 
  server: 
  type: 
  fixed: 
  autoplay: 
  loop: 
  order: 
  preload: 
  volume: 
  mutex: 

# Valine
valine: 
v_appId: 
v_appKey: 

# Waline
waline:
  enable: 
  serverURL:
  visitor:
  comment_count:
  avatar: 
  guest_info: 
  pageSize: 
  placeholder: 
  requiredFields: 
  background: 